language: python
python:
  - "2.7"
install: sudo apt-get update && sudo apt-get install -y python-virtualenv python-scipy g++ libav-tools && ./bootstrap.sh
script: ./bin/python bin/list-tests.py
notifications:
  email:
    recipients:
      - wlachance@mozilla.com
